import pandas as pd
from PlotMe import PlotMe

# Read sales data from CSV file
sales_data_df = pd.read_csv("GeographicDataAnalysis.csv")
# print(sales_data_df.head())
# print(sales_data_df.columns)

sales_data = {
    "State": [
        "Montana",
        "American Samoa",
        "North Carolina",
        "Nebraska",
        "Florida",
        "Kentucky",
        "Georgia",
        "Massachusetts",
        "South Carolina",
        "Alabama",
        "Oklahoma",
        "Iowa",
        "Nevada",
        "Maine",
        "Utah",
        "Trust Territories",
        "Idaho",
        "Arkansas",
        "Kansas",
        "Iowa",
        "New Jersey",
        "Puerto Rico",
        "Arkansas",
        "Texas",
        "New Mexico",
        "Utah",
        "West Virginia",
        "Utah",
        "Michigan",
        "Georgia",
        "Oklahoma",
        "New Hampshire",
        "Washington",
        "Mississippi",
        "North Carolina",
        "Arizona",
        "Alaska",
        "Texas",
        "Maryland",
        "West Virginia",
        "Nevada",
        "Illinois",
        "Oregon",
        "Guam",
        "Arizona",
        "Hawaii",
        "Oklahoma",
        "Connecticut",
        "Trust Territories",
    ],
    "Abbr": [
        "MT",
        "AS",
        "NC",
        "NE",
        "FL",
        "KY",
        "GA",
        "MA",
        "SC",
        "AL",
        "OK",
        "IA",
        "NV",
        "ME",
        "UT",
        "TT",
        "ID",
        "AR",
        "KS",
        "IA",
        "NJ",
        "PR",
        "AR",
        "TX",
        "NM",
        "UT",
        "WV",
        "UT",
        "MI",
        "GA",
        "OK",
        "NH",
        "WA",
        "MS",
        "NC",
        "AZ",
        "AK",
        "TX",
        "MD",
        "WV",
        "NV",
        "IL",
        "OR",
        "GU",
        "AZ",
        "HI",
        "OK",
        "CT",
        "TT",
    ],
    "SalesPerson": [
        "Maria Garcia",
        "Miguel Fernandez",
        "Isabella Rossi",
        "Aisha Abubakar",
        "David Kim",
        "Jamal Al-Farsi",
        "Fatima Mohamed",
        "Marcelo Silva",
        "Liu Wei",
        "Aisha Abubakar",
        "Fatima Mohamed",
        "Leila Abadi",
        "Yuki Tanaka",
        "Mohammed Khan",
        "Aisha Abubakar",
        "Leila Abadi",
        "Yuri Petrov",
        "Isabella Rossi",
        "Liu Wei",
        "Ingrid Svensson",
        "Miguel Fernandez",
        "Anna Nowak",
        "Juan Lopez",
        "Miguel Fernandez",
        "Marcelo Silva",
        "Mohammed Khan",
        "Ahmed Hassan",
        "Mohammed Khan",
        "Miguel Fernandez",
        "Liu Wei",
        "Jamal Al-Farsi",
        "Marcelo Silva",
        "Marcelo Silva",
        "Marcelo Silva",
        "Aisha Abubakar",
        "Liu Wei",
        "Nguyen Minh",
        "Liu Wei",
        "Marcelo Silva",
        "Ingrid Svensson",
        "Maria Garcia",
        "David Kim",
        "Ingrid Svensson",
        "Yuri Petrov",
        "Fatima Mohamed",
        "Fatima Mohamed",
        "Marcelo Silva",
        "Liu Wei",
        "Carlos Rodriguez",
    ],
    "SalesValue": [
        "4201233",
        "2676289",
        "1542477",
        "5623511",
        "19592732",
        "8223227",
        "3155125",
        "4852290",
        "13274352",
        "8086450",
        "21865011",
        "2093316",
        "1674386",
        "15061309",
        "8303224",
        "12919180",
        "4740179",
        "2879853",
        "1494929",
        "1915578",
        "1959748",
        "21389101",
        "7858976",
        "5389744",
        "14113406",
        "4046864",
        "8223104",
        "13177766",
        "5631059",
        "18150027",
        "4650358",
        "6606012",
        "4104061",
        "4515086",
        "17133129",
        "14278440",
        "5757716",
        "4746969",
        "14938552",
        "3429175",
        "4473725",
        "4973601",
        "14982679",
        "15887715",
        "20913810",
        "1351147",
        "5418668",
        "566787",
        "23290435",
    ],
    "Region": [
        "West",
        "South-West",
        "East",
        "South-West",
        "North",
        "South-West",
        "West",
        "South",
        "South",
        "East",
        "South",
        "South-East",
        "North-East",
        "South-West",
        "North-West",
        "South-West",
        "South",
        "East",
        "South",
        "South",
        "South",
        "South",
        "South-East",
        "East",
        "South-East",
        "South-East",
        "North",
        "South-East",
        "West",
        "North-East",
        "East",
        "West",
        "South-East",
        "East",
        "South",
        "North",
        "North",
        "North-West",
        "North",
        "South-West",
        "East",
        "East",
        "West",
        "North-East",
        "East",
        "West",
        "East",
        "South-West",
        "West",
    ],
}

# Convert DataFrame to dictionary
sales_data = {
    'State': sales_data_df['State'].to_list(),
    'SalesPerson': sales_data_df['SalesPerson'].to_list(),
    'SalesValue': sales_data_df['SalesValue'].to_list(),
    'Region': sales_data_df['Region'].to_list(),
}

print(sales_data)

# Instantiate SalesMap class and generate the map
sales_map = PlotMe("ne_110m_admin_1_states_provinces.shp", sales_data)

# to Generate MAP for total sales
sales_map.generate_total_sales_map()

# to Generate MAP for specific Filter
# sales_map.generate_sales_map(State="New York", Region="East")
